# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Pizzeria.create([
  {
    city: "Phoenix",
    state: "Arizona",
    country: "United States",
    name: "Pizzeria Bianco",
    website: "http://www.pizzeriabianco.com/",
    address: "623 E. Adams St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "33.4491602",
    lng: "-112.0656345"
  },
  {
    city: "Berkeley",
    state: "California",
    country: "United States",
    name: "The Cheese Board Collective",
    website: "http://cheeseboardcollective.coop/",
    address: "1504 Shattuck Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.8799915",
    lng: "-122.2694861"
  },
  {
    city: "Berkeley",
    state: "California",
    country: "United States",
    name: "Emilia's",
    website: "http://emiliaspizzeria.com/",
    address: "2995 Shattuck Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.8555266",
    lng: "-122.2662672"
  },
  {
    city: "Chico",
    state: "California",
    country: "United States",
    name: "Celestino's",
    website: "http://www.celestinosnypizza.com/",
    address: "101 Salem Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7298093",
    lng: "-121.8427506"
  },
  {
    city: "Los Angeles",
    state: "California",
    country: "United States",
    name: "Pizzanista",
    website: "http://www.pizzanista.com/",
    address: "2019 E 7th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "34.0348332",
    lng: "-118.2316054"
  },
  {
    city: "Oakland",
    state: "California",
    country: "United States",
    name: "Hi-Life",
    website: "http://www.hilifeoakland.com",
    address: "400 15th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.805068",
    lng: "-122.2694895"
  },
  {
    city: "Oakland",
    state: "California",
    country: "United States",
    name: "Nicks",
    website: "http://oaklandstylepizza.com/",
    address: "6211 Shattuck Ave.",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.8482849",
    lng: "-122.2657307"
  },
  {
    city: "Oakland",
    state: "California",
    country: "United States",
    name: "Zachary's",
    website: "http://zacharys.com/locations/oakland",
    address: "5801 College Ave.",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.8462952",
    lng: "-122.252171"
  },
  {
    city: "Palo Alto",
    state: "California",
    country: "United States",
    name: "Terun",
    website: "http://terunpizza.com/",
    address: "448 S. California Ave.",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.4259205",
    lng: "-122.1454743"
  },
  {
    city: "Sacramento",
    state: "California",
    country: "United States",
    name: "Pieces Pizza",
    website: "https://www.yelp.com/biz/pieces-pizza-by-the-slice-sacramento/",
    address: "1309 21st St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "-121.480032",
    lng: "38.572606"
  },
  {
    city: "San Diego",
    state: "California",
    country: "United States",
    name: "Newport Pizza and Ale House",
    website: "http://www.yelp.com/biz/newport-pizza-and-ale-house-san-diego",
    address: "5050 Newport Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "32.74761",
    lng: "-117.2518458"
  },
  {
    city: "San Diego",
    state: "California",
    country: "United States",
    name: "Pizza Port",
    website: "http://www.pizzaport.com",
    address: "1956 Bacon St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "32.7479652",
    lng: "-117.250302"
  },
  {
    city: "San Diego",
    state: "California",
    country: "United States",
    name: "Pizzeria Luigi",
    website: "http://www.pizzerialuigi.com/",
    address: "2121 El Cajon Blvd.",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "32.7549265",
    lng: "-117.1419584"
  },
  {
    city: "San Diego",
    state: "California",
    country: "United States",
    name: "Sicilian Thing Pizza",
    website: "http://www.sicilianthingpizza.com/",
    address: "4046 30th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "32.7512644",
    lng: "-117.1304495"
  },
  {
    city: "San Francisco",
    state: "California",
    country: "United States",
    name: "Golden Boy",
    website: "http://www.goldenboypizza.com/",
    address: "542 Green St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.79983540000001",
    lng: "-122.4080836"
  },
  {
    city: "San Francisco",
    state: "California",
    country: "United States",
    name: "Little Star",
    website: "http://www.littlestarpizza.com/",
    address: "846 Divisadero St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.7775481",
    lng: "-122.4380073"
  },
  {
    city: "San Francisco",
    state: "California",
    country: "United States",
    name: "Tonyâ€™s Pizza Napoletana",
    website: "http://tonyspizzanapoletana.com/",
    address: "1570 Stockton St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.80032569999999",
    lng: "-122.408985"
  },
  {
    city: "San Francisco",
    state: "California",
    country: "United States",
    name: "Una Pizza Napoletana",
    website: "http://www.unapizza.com/",
    address: "210 11th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "37.7728347",
    lng: "-122.4155562"
  },
  {
    city: "Santa Monica",
    state: "California",
    country: "United States",
    name: "Milo & Olive",
    website: "http://www.miloandolive.com/",
    address: "2723 Wilshire Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "34.03755960000001",
    lng: "-118.4760519"
  },
  {
    city: "Santa Monica",
    state: "California",
    country: "United States",
    name: "NY&C",
    website: "http://www.nyandcpizza.com/home.html",
    address: "1120 Wilshire Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "34.0247879",
    lng: "-118.491037"
  },
  {
    city: "Santa Monica",
    state: "California",
    country: "United States",
    name: "Stella Barra",
    website: "http://www.stellabarra.com/",
    address: "2000 Main St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "34.0066779",
    lng: "-118.4887734"
  },
  {
    city: "Boulder",
    state: "Colorado",
    country: "United States",
    name: "Pizzeria Locale",
    website: "http://localeboulder.com/",
    address: "1730 Pearl St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.0192033",
    lng: "-105.2726228"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Lucky Pie",
    website: "http://www.luckypiepizza.com/lodo/",
    address: "1610 16th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7512096",
    lng: "-105.0005432"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Denver Pizza Company",
    website: "http://www.denverpizzaco.com/",
    address: "309 W 11th Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7340381",
    lng: "-104.9920459"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Benny Blancos",
    website: "http://www.yelp.com/biz/benny-blancos-denver",
    address: "616 E 13th Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.736768",
    lng: "-104.979363"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Blue Pan Pizza",
    website: "http://bluepandenver.com/",
    address: "3930 W 32nd Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7619696",
    lng: "-105.0388204"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Fat Sully's",
    website: "http://www.fatsullys.com",
    address: "3237 E Colfax Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7403795",
    lng: "-104.9490983"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Grimaldi's Pizzeria",
    website: "http://www.grimaldispizzeria.com/",
    address: "500 16th Street, Unit 128",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7435013",
    lng: "-104.9908942"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Pizza Pedalr",
    website: "http://www.pizzapedalr.com/",
    address: "2907 Huron Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7586172",
    lng: "-104.9974253"
  },
  {
    city: "Denver",
    state: "Colorado",
    country: "United States",
    name: "Cart Driver",
    website: "http://cart-driver.com/",
    address: "2500 Larimer Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.7576428",
    lng: "-104.9861259"
  },
  {
    city: "Westminster",
    state: "Colorado",
    country: "United States",
    name: "The Garlic Knot",
    website: "http://www.garlicknotpizza.com/",
    address: "7727 W 92nd Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.8644326",
    lng: "-105.0833725"
  },
  {
    city: "New Haven",
    state: "Connecticut",
    country: "United States",
    name: "Da Legna",
    website: "http://dalegna.com/",
    address: "858 State St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.3134495",
    lng: "-72.9134709"
  },
  {
    city: "New Haven",
    state: "Connecticut",
    country: "United States",
    name: "Modern Apizza",
    website: "http://www.modernapizza.com/",
    address: "874 State St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.3138525",
    lng: "-72.9129229"
  },
  {
    city: "New Haven",
    state: "Connecticut",
    country: "United States",
    name: "Pepe's",
    website: "http://pepespizzeria.com/",
    address: "157 Wooster St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.302821",
    lng: "-72.9169246"
  },
  {
    city: "New Haven",
    state: "Connecticut",
    country: "United States",
    name: "Sally's Apizza",
    website: "http://www.sallysapizza.com/",
    address: "237 Wooster St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.3031344",
    lng: "-72.9200181"
  },
  {
    city: "Washington",
    state: "District of Columbia",
    country: "United States",
    name: "2 Amys",
    website: "http://2amys.tripod.com/",
    address: "3715 Macomb St NW",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.9336232",
    lng: "-77.073091"
  },
  {
    city: "Washington",
    state: "District of Columbia",
    country: "United States",
    name: "Comet Ping Pong",
    website: "http://www.cometpingpong.com/",
    address: "5037 Connecticut Ave NW",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.9559497",
    lng: "-77.0699666"
  },
  {
    city: "Washington",
    state: "District of Columbia",
    country: "United States",
    name: "Matchbox Pizza",
    website: "http://www.matchboxrestaurants.com/",
    address: "713 H St NW",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.9000448",
    lng: "-77.0224838"
  },
  {
    city: "Washington",
    state: "District of Columbia",
    country: "United States",
    name: "Pete's New Haven Pizza",
    website: "http://petesapizza.com/",
    address: "1400 Irving St NW #103",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.9284986",
    lng: "-77.0335765"
  },
  {
    city: "Gainesville",
    state: "Florida",
    country: "United States",
    name: "Big Lou's",
    website: "http://www.biglouspizzeria.com/",
    address: "5 SE 2nd Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "29.6500345",
    lng: "-82.3247497"
  },
  {
    city: "Gainesville",
    state: "Florida",
    country: "United States",
    name: "Leonardo's",
    website: "http://www.leonardosgainesville.com/",
    address: "1245 W University Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "29.6518385",
    lng: "-82.33860050000001"
  },
  {
    city: "Gainesville",
    state: "Florida",
    country: "United States",
    name: "Satchel's",
    website: "http://www.satchelspizza.com/",
    address: "1800 NE 23rd Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "29.6739783",
    lng: "-82.3019018"
  },
  {
    city: "Orlando",
    state: "Florida",
    country: "United States",
    name: "Lazy Moon",
    website: "http://www.lazymoonpizza.com/",
    address: "11551 University Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "28.5983382",
    lng: "-81.21971219999999"
  },
  {
    city: "Atlanta",
    state: "Georgia",
    country: "United States",
    name: "Ammazza",
    website: "http://ammazza.com/",
    address: "591 Edgewood Ave SE",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "33.7540633",
    lng: "-84.3680959"
  },
  {
    city: "Atlanta",
    state: "Georgia",
    country: "United States",
    name: "Antico Pizza Napoletana",
    website: "http://littleitalia.com/",
    address: "1093 Hemphill Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "33.7846513",
    lng: "-84.40558899999999"
  },
  {
    city: "Atlanta",
    state: "Georgia",
    country: "United States",
    name: "Double Zero",
    website: "http://www.doublezeroatl.com/",
    address: "5825 Roswell Road Northeast",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "33.9143625",
    lng: "-84.3788008"
  },
  {
    city: "Atlanta",
    state: "Georgia",
    country: "United States",
    name: "St. Angelo's",
    website: "http://www.stangelos.com/",
    address: "4686 S Atlanta Rd SE",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "33.8399724",
    lng: "-84.4839738"
  },
  {
    city: "Chicago",
    state: "Illinois",
    country: "United States",
    name: "Coalfire",
    website: "http://coalfirechicago.com/menu/index.html",
    address: "1321 W Grand Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.890838",
    lng: "-87.65985769999999"
  },
  {
    city: "Chicago",
    state: "Illinois",
    country: "United States",
    name: "Piece",
    website: "http://www.piecechicago.com/pizza.php",
    address: "1927 W North Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.9102999",
    lng: "-87.676129"
  },
  {
    city: "Chicago",
    state: "Illinois",
    country: "United States",
    name: "Pequod's",
    website: "http://pequodspizza.com",
    address: "2207 N. Clybourn Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.921931",
    lng: "-87.66430749999999"
  },
  {
    city: "Chicago",
    state: "Illinois",
    country: "United States",
    name: "Santullo's",
    website: "http://www.santullos.com",
    address: "1943 W North Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.9103688",
    lng: "-87.6767737"
  },
  {
    city: "Coal Valley",
    state: "Illinois",
    country: "United States",
    name: "Happy Joe's Pizza & Ice Cream",
    website: "http://www.happyjoes.com",
    address: "320 West 1st Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.4530828",
    lng: "-90.4642188"
  },
  {
    city: "Rock Island",
    state: "Illinois",
    country: "United States",
    name: "Harris Pizza",
    website: "http://www.harrispizza.com",
    address: "3903 14th Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.497507",
    lng: "-90.5461894"
  },
  {
    city: "Rockford",
    state: "Illinois",
    country: "United States",
    name: "Toni's Pizza",
    website: "http://www.tonispizzaandpasta.com/",
    address: "457 N Milwaukee Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.50136",
    lng: "-89.0217747"
  },
  {
    city: "Bloomington",
    state: "Indiana",
    country: "United States",
    name: "Mother Bear's",
    website: "http://www.someguyspizza.com/",
    address: "6235 Allisonville Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "44.840798",
    lng: "-93.2982799"
  },
  {
    city: "Bloomington",
    state: "Indiana",
    country: "United States",
    name: "Pizza X",
    website: "http://www.pizzaxbloomington.com/",
    address: "1791 E. 10th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.1715861",
    lng: "-86.51095749999999"
  },
  {
    city: "Indianapolis",
    state: "Indiana",
    country: "United States",
    name: "Napolese",
    website: "http://napolesepizzeria.com",
    address: "30 S Meridian St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.766037",
    lng: "-86.1584558"
  },
  {
    city: "Indianapolis",
    state: "Indiana",
    country: "United States",
    name: "Some Guys",
    website: "http://www.someguyspizza.com/",
    address: "6235 Allisonville Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.8699814",
    lng: "-86.0955293"
  },
  {
    city: "South Bend",
    state: "Indiana",
    country: "United States",
    name: "Barnaby's",
    website: "http://www.barnabys-pizza.com/",
    address: "713 E. Jefferson Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.6753558",
    lng: "-86.24091969999999"
  },
  {
    city: "South Bend",
    state: "Indiana",
    country: "United States",
    name: "Bruno's",
    website: "http://www.brunospizza.com/",
    address: "2202 E Mishawaka Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.665453",
    lng: "-86.2148295"
  },
  {
    city: "Boston",
    state: "Massachusetts",
    country: "United States",
    name: "Big Daddy's Pizza",
    website: "http://bigdaddyspizza.biz/",
    address: "436 Western Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.3622619",
    lng: "-71.14094419999999"
  },
  {
    city: "Boston",
    state: "Massachusetts",
    country: "United States",
    name: "Pizzeria Regina",
    website: "http://www.pizzeriaregina.com/",
    address: "226 Faneuil Hall Market Place",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.3597994",
    lng: "-71.0544602"
  },
  {
    city: "Boston",
    state: "Massachusetts",
    country: "United States",
    name: "Santarpio's Pizza",
    website: "http://www.santarpiospizza.com/",
    address: "111 Chelsea Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.3726652",
    lng: "-71.0352715"
  },
  {
    city: "Cambridge",
    state: "Massachusetts",
    country: "United States",
    name: "Pinocchio's Pizza & Subs",
    website: "http://www.pinocchiospizza.net/",
    address: "74 Winthrop Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.3719942",
    lng: "-71.120359"
  },
  {
    city: "Detroit",
    state: "Michigan",
    country: "United States",
    name: "Supino Pizzeria",
    website: "http://supinopizzeria.com/",
    address: "2457 Russell St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.3453855",
    lng: "-83.0402498"
  },
  {
    city: "Holland",
    state: "Michigan",
    country: "United States",
    name: "Fricano's Too",
    website: "http://www.fricanospizza.com/",
    address: "174 S River Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.7908875",
    lng: "-86.109286"
  },
  {
    city: "Saint Paul / Minneapolis",
    state: "Minnesota",
    country: "United States",
    name: "Pizza LucÃ©",
    website: "https://pizzaluce.com/",
    address: "119 N 4th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "44.9816029",
    lng: "-93.27374329999999"
  },
  {
    city: "Saint Paul / Minneapolis",
    state: "Minnesota",
    country: "United States",
    name: "Punch Neapolitan Pizza",
    website: "http://www.punchpizza.com/",
    address: "210 E Hennepin Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "44.9875163",
    lng: "-93.2568974"
  },
  {
    city: "Columbia, MO",
    state: "Missouri",
    country: "United States",
    name: "Shakespeare's Pizza",
    website: "http://shakespeares.com/",
    address: "225 S 9th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.9486734",
    lng: "-92.32792289999999"
  },
  {
    city: "St. Louis",
    state: "Missouri",
    country: "United States",
    name: "Dewey's Pizza",
    website: "http://www.deweyspizza.com",
    address: "559 N and South Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.6590335",
    lng: "-90.33792489999999"
  },
  {
    city: "St. Louis",
    state: "Missouri",
    country: "United States",
    name: "Joe Boccardi's Ristorante",
    website: "http://www.joeboccardis.com/",
    address: "8556 Watson Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.56472300000001",
    lng: "-90.357811"
  },
  {
    city: "St. Louis",
    state: "Missouri",
    country: "United States",
    name: "Imo's Pizza",
    website: "http://imospizza.com/",
    address: "1828 Washington Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.6334951",
    lng: "-90.20616419999999"
  },
  {
    city: "St. Louis",
    state: "Missouri",
    country: "United States",
    name: "Pi Pizzeria",
    website: "http://pi-pizza.com",
    address: "6144 Delmar Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.65501260000001",
    lng: "-90.2977494"
  },
  {
    city: "St. Louis",
    state: "Missouri",
    country: "United States",
    name: "Randolfi's",
    website: "https://twitter.com/randolfisstl",
    address: "6665 Delmar",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "38.656469",
    lng: "-90.30756099999999"
  },
  {
    city: "Lincoln",
    state: "Nebraska",
    country: "United States",
    name: "YiaYia's",
    website: "http://yiayiaspizza.com/",
    address: "1423 O St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.8132565",
    lng: "-96.70047389999999"
  },
  {
    city: "Omaha",
    state: "Nebraska",
    country: "United States",
    name: "Pitch Pizzeria",
    website: "http://www.pitchpizzeria.com",
    address: "5021 Underwood Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.2648322",
    lng: "-95.9921566"
  },
  {
    city: "Omaha",
    state: "Nebraska",
    country: "United States",
    name: "Pitch Pizzeria",
    website: "http://www.pitchpizzeria.com",
    address: "17808 Burke St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "41.2578015",
    lng: "-96.1919798"
  },
  {
    city: "Henderson",
    state: "Nevada",
    country: "United States",
    name: "Settebello",
    website: "http://settebello.net/",
    address: "140 S Green Valley Pkwy",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "36.022463",
    lng: "-115.0833621"
  },
  {
    city: "Manchester",
    state: "New Hampshire",
    country: "United States",
    name: "Jimmy's House of Pizza",
    website: "http://www.yelp.com/biz/jimmys-house-of-pizza-manchester",
    address: "345 Kelley St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.995535",
    lng: "-71.4852102"
  },
  {
    city: "Manchester",
    state: "New Hampshire",
    country: "United States",
    name: "Ollie's",
    website: "http://www.yelp.com/biz/ollies-manchester",
    address: "761 Mast Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.9902202",
    lng: "-71.49885840000002"
  },
  {
    city: "Manchester",
    state: "New Hampshire",
    country: "United States",
    name: "Pizza Market",
    website: "http://www.pizzamarket.net/",
    address: "845 Hanover St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.987751",
    lng: "-71.4282836"
  },
  {
    city: "Jersey City",
    state: "New Jersey",
    country: "United States",
    name: "Porta Pizza",
    website: "http://pizzaporta.com/",
    address: "911 Kingsley St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.2202394",
    lng: "-74.0023444"
  },
  {
    city: "Avenel",
    state: "New Jersey",
    country: "United States",
    name: "Pizza Time",
    website: "http://www.pizzatimenj.com/",
    address: "1076 St Georges Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.5755949",
    lng: "-74.2939839"
  },
  {
    city: "Freehold",
    state: "New Jersey",
    country: "United States",
    name: "Vinnie's Pizza",
    website: "http://www.vinpizza.com/",
    address: "3249 U.S. 9",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.2195867",
    lng: "-74.2651407"
  },
  {
    city: "Hamilton",
    state: "New Jersey",
    country: "United States",
    name: "DeLorenzo's Pizza",
    website: "https://www.facebook.com/delorenzos?fref=ts",
    address: "147 Sloan Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.2495329",
    lng: "-74.68923509999999"
  },
  {
    city: "Hoboken",
    state: "New Jersey",
    country: "United States",
    name: "Mario's Classic Pizza",
    website: "http://mariosclassicpizza.com/",
    address: "742 Garden St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.746258",
    lng: "-74.0302316"
  },
  {
    city: "Jersey City",
    state: "New Jersey",
    country: "United States",
    name: "Porta Pizza",
    website: "http://pizzaporta.com/",
    address: "135 Newark Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7202039",
    lng: "-74.043695"
  },
  {
    city: "Jersey City",
    state: "New Jersey",
    country: "United States",
    name: "Razza",
    website: "http://www.razzanj.com/",
    address: "275 Grove St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7177598",
    lng: "-74.0442614"
  },
  {
    city: "Neptune",
    state: "New Jersey",
    country: "United States",
    name: "Pete & Elda's / Carmen's Pizzeria",
    website: "http://www.peteandeldas.com/",
    address: "96 Woodland Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.19906410000001",
    lng: "-74.0289882"
  },
  {
    city: "Manahawkin",
    state: "New Jersey",
    country: "United States",
    name: "Anthony's Pizza",
    website: "http://www.yelp.com/biz/anthonys-restaurant-and-pizzeria-manahawkin",
    address: "857 Mill Creek Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.676731",
    lng: "-74.235832"
  },
  {
    city: "Woodbridge",
    state: "New Jersey",
    country: "United States",
    name: "San Remo Pizza",
    website: "http://www.sanremopizza.net/",
    address: "87 Main St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.5539364",
    lng: "-74.2800736"
  },
  {
    city: "Albuquerque",
    state: "New Mexico",
    country: "United States",
    name: "Farina",
    website: "http://www.farinapizzeria.com/",
    address: "510 Central Ave SE",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.0830931",
    lng: "-106.6418247"
  },
  {
    city: "Albuquerque",
    state: "New Mexico",
    country: "United States",
    name: "Giovanni's",
    website: "http://www.giovannispizzaalbuquerque.com/",
    address: "921 San Pedro Dr SE",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.06473",
    lng: "-106.578195"
  },
  {
    city: "Albuquerque",
    state: "New Mexico",
    country: "United States",
    name: "Slice Parlor",
    website: "http://www.sliceparlor.com/",
    address: "3410 Central Ave SE",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.0797725",
    lng: "-106.6064885"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "Forcella",
    website: "http://forcellaeatery.com/williamsburg/",
    address: "485 Lorimer St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7114916",
    lng: "-73.9492046"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "Franny's",
    website: "http://frannysbrooklyn.com/",
    address: "348 Flatbush Avenue",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.6759441",
    lng: "-73.971842"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "Lucali",
    website: "http://www.lucali.com/",
    address: "575 Henry Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.6818032",
    lng: "-74.00030869999999"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "Luigi's Pizza",
    website: "http://www.yelp.com/biz/luigi-pizzeria-brooklyn",
    address: "686 5th Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.6616446",
    lng: "-73.9934097"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "My Little Pizzeria",
    website: "http://www.yelp.com/biz/my-little-pizzeria-brooklyn",
    address: "114 Court St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.6902372",
    lng: "-73.99233819999999"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "Paulie Gee's",
    website: "http://pauliegee.com/",
    address: "60 Greenpoint Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7295613",
    lng: "-73.95856979999999"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "Roberta's",
    website: "http://www.robertaspizza.com/",
    address: "261 Moore St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7050888",
    lng: "-73.9335849"
  },
  {
    city: "Brooklyn",
    state: "New York",
    country: "United States",
    name: "Saraghina",
    website: "http://www.saraghinabrooklyn.com",
    address: "435 Halsey St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.6836221",
    lng: "-73.93535849999999"
  },
  {
    city: "Buffalo",
    state: "New York",
    country: "United States",
    name: "Pizza By Molino's",
    website: "http://www.pizzabymolinos.com/",
    address: "1974 Clinton St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "42.8719685",
    lng: "-78.8035302"
  },
  {
    city: "NYC",
    state: "New York",
    country: "United States",
    name: "Adrienne's Pizza Bar",
    website: "http://www.adriennespizzabarnyc.com/",
    address: "54 Stone St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7042851",
    lng: "-74.0101208"
  },
  {
    city: "NYC",
    state: "New York",
    country: "United States",
    name: "John's of Bleeker St",
    website: "http://www.johnsbrickovenpizza.com/",
    address: "278 Bleecker St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7316187",
    lng: "-74.00344679999999"
  },
  {
    city: "NYC",
    state: "New York",
    country: "United States",
    name: "Lombardi's",
    website: "http://www.firstpizza.com/",
    address: "32 Spring St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7215332",
    lng: "-73.99563440000001"
  },
  {
    city: "NYC",
    state: "New York",
    country: "United States",
    name: "Motorino",
    website: "http://www.motorinopizza.com/",
    address: "349 East 12th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7303588",
    lng: "-73.9838278"
  },
  {
    city: "NYC",
    state: "New York",
    country: "United States",
    name: "Prince Street Pizza",
    website: "http://www.yelp.com/biz/prince-st-pizza-new-york",
    address: "27 Prince St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7230686",
    lng: "-73.99454949999999"
  },
  {
    city: "NYC",
    state: "New York",
    country: "United States",
    name: "Saluggi's",
    website: "http://www.saluggis.com/",
    address: "325 Church St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.72010400000001",
    lng: "-74.0035747"
  },
  {
    city: "Staten Island",
    state: "New York",
    country: "United States",
    name: "Joe and Pat's",
    website: "http://www.yelp.com/biz/joe-and-pats-staten-island",
    address: "1758 Victory Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.612924",
    lng: "-74.1221376"
  },
  {
    city: "Syracuse",
    state: "New York",
    country: "United States",
    name: "Patsy's Pizza",
    website: "http://www.patsyspizza.net/",
    address: "1205 Erie Boulevard W",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.0505278",
    lng: "-76.1804489"
  },
  {
    city: "Syracuse",
    state: "New York",
    country: "United States",
    name: "Varsity Pizza",
    website: "http://www.yelp.com/biz/varsity-pizza-syracuse",
    address: "802 S Crouse Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.041475",
    lng: "-76.1370309"
  },
  {
    city: "Asheville",
    state: "North Carolina",
    country: "United States",
    name: "Favilla's New York Pizza",
    website: "http://www.favillasnypizza.com",
    address: "1093 Patton Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.5872512",
    lng: "-82.5959249"
  },
  {
    city: "Asheville",
    state: "North Carolina",
    country: "United States",
    name: "Standard Pizza Co.",
    website: "http://www.standardpizzacoasheville.com",
    address: "631 Haywood Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.5787982",
    lng: "-82.58943909999999"
  },
  {
    city: "Chapel Hill/Carrboro",
    state: "North Carolina",
    country: "United States",
    name: "Alfredo's Pizza Villa",
    website: "http://www.alfredospizzanc.com/",
    address: "201 S Estes Dr",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.9278462",
    lng: "-79.02687829999999"
  },
  {
    city: "Chapel Hill/Carrboro",
    state: "North Carolina",
    country: "United States",
    name: "Amante",
    website: "http://amantepizza.com",
    address: "300 E Main St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.9100097",
    lng: "-79.0687289"
  },
  {
    city: "Durham",
    state: "North Carolina",
    country: "United States",
    name: "Pizzeria Toro",
    website: "http://www.pizzeriatoro.com",
    address: "105 E Chapel Hill St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.9971175",
    lng: "-78.9036011"
  },
  {
    city: "Raleigh",
    state: "North Carolina",
    country: "United States",
    name: "Lilly's",
    website: "http://lillyspizza.com",
    address: "810 W Peabody St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "32.7480092",
    lng: "-96.54636769999999"
  },
  {
    city: "Raleigh",
    state: "North Carolina",
    country: "United States",
    name: "Capital Creations",
    website: "http://capitalcreations.com",
    address: "1842 Wake Forest Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.8055722",
    lng: "-78.6244486"
  },
  {
    city: "Raleigh",
    state: "North Carolina",
    country: "United States",
    name: "Lilly's",
    website: "http://lillyspizza.com",
    address: "1813 Glenwood Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.8050358",
    lng: "-78.64673599999999"
  },
  {
    city: "Raleigh",
    state: "North Carolina",
    country: "United States",
    name: "Mellow Mushroom",
    website: "http://mellowmushroom.com/store/raleigh",
    address: "601 W Peace St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.7883498",
    lng: "-78.6474466"
  },
  {
    city: "Columbus",
    state: "Ohio",
    country: "United States",
    name: "Emelio's",
    website: "http://www.emelioscatering.com",
    address: "574 Georgesville Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.9411137",
    lng: "-83.11158089999999"
  },
  {
    city: "Powell",
    state: "Ohio",
    country: "United States",
    name: "Brooklyn Pizza",
    website: "http://www.brooklynpizzapowell.com",
    address: "240 North Liberty St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.1628348",
    lng: "-83.07495279999999"
  },
  {
    city: "Oklahoma City",
    state: "Oklahoma",
    country: "United States",
    name: "Empire Slice House",
    website: "http://www.empireslicehouse.com/",
    address: "1734 NW 16th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.4857302",
    lng: "-97.540545"
  },
  {
    city: "Oklahoma City",
    state: "Oklahoma",
    country: "United States",
    name: "Slice House",
    website: "http://slicehouse2ndst.com/",
    address: "680 2nd St.",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.1379387",
    lng: "-97.6561345"
  },
  {
    city: "Eugene",
    state: "Oregon",
    country: "United States",
    name: "Pizza Research Institute",
    website: "http://www.pizzaresearchinstitute.com/",
    address: "325 Blair Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "44.0562318",
    lng: "-123.1096949"
  },
  {
    city: "Portland",
    state: "Oregon",
    country: "United States",
    name: "Apizza Scholls",
    website: "http://apizzascholls.com/",
    address: "4741 SE Hawthorne Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "45.512267",
    lng: "-122.613116"
  },
  {
    city: "Portland",
    state: "Oregon",
    country: "United States",
    name: "Ken's Artisan",
    website: "http://kensartisan.com/",
    address: "338 NW 21st Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "45.5254201",
    lng: "-122.6942071"
  },
  {
    city: "Portland",
    state: "Oregon",
    country: "United States",
    name: "Pyro Pizza",
    website: "http://pyropizzacart.com/",
    address: "1204 SE Hawthorne Blvd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "45.512489",
    lng: "-122.653512"
  },
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "United States",
    name: "Blackbird Pizzeria",
    website: "http://blackbirdpizzeria.com/",
    address: "507 S 6th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.9426904",
    lng: "-75.1519979"
  },
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "United States",
    name: "Dock Street Brewery",
    website: "http://www.dockstreetbeer.com/",
    address: "701 South 50th Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.9476806",
    lng: "-75.22270689999999"
  },
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "United States",
    name: "Gennaro's Tomato Pie",
    website: "https://www.facebook.com/GennarosTomatoPie",
    address: "1429 Jackson St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.923454",
    lng: "-75.171167"
  },
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "United States",
    name: "In Riva",
    website: "http://www.in-riva.com/images/menuDINNER.pdf",
    address: "4116 Ridge Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.0078651",
    lng: "-75.19244290000002"
  },
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "United States",
    name: "Nomad Pizza Co",
    website: "http://www.nomadpizzaco.com/",
    address: "611 S 7th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.9418369",
    lng: "-75.15383709999999"
  },
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "United States",
    name: "Pizzeria Beddia",
    website: "https://pizzeriabeddia.wordpress.com",
    address: "115 E Girard Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.9692304",
    lng: "-75.1339393"
  },
  {
    city: "Philadelphia",
    state: "Pennsylvania",
    country: "United States",
    name: "Tacconelli's",
    website: "http://www.tacconellispizzeria.com",
    address: "2604 E Somerset St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "39.9803819",
    lng: "-75.1131393"
  },
  {
    city: "Pittsburgh",
    state: "Pennsylvania",
    country: "United States",
    name: "Aiello's Pizza",
    website: "http://aiellospizza.com/",
    address: "2112 Murray Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.4332608",
    lng: "-79.9231982"
  },
  {
    city: "Pottsville",
    state: "Pennsylvania",
    country: "United States",
    name: "Palermo Pizza & Restaurant",
    website: "http://palermopizzarestaurant.com/",
    address: "Kings Plaza Pottsville-Miner Hwy",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.6856456",
    lng: "-76.195499"
  },
  {
    city: "Pottsville",
    state: "Pennsylvania",
    country: "United States",
    name: "Roma Pizza",
    website: "http://www.romapizzapottsville.com/",
    address: "116 W Market St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.6856335",
    lng: "-76.19639839999999"
  },
  {
    city: "Nashville",
    state: "Tennessee",
    country: "United States",
    name: "Desano Pizza Bakery",
    website: "http://desanopizza.it/",
    address: "115 16th Avenue",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "36.1468244",
    lng: "-86.7925321"
  },
  {
    city: "Nashville",
    state: "Tennessee",
    country: "United States",
    name: "Five Points Pizza",
    website: "http://www.fivepointspizza.com/",
    address: "1012 Woodland St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "36.1771287",
    lng: "-86.7505102"
  },
  {
    city: "Austin",
    state: "Texas",
    country: "United States",
    name: "40 North",
    website: "http://www.40northpizza.com",
    address: "1502 S 1st St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "30.2500751",
    lng: "-97.7555357"
  },
  {
    city: "Austin",
    state: "Texas",
    country: "United States",
    name: "The Austin Beer Garden Brewing Company",
    website: "http://theabgb.com/",
    address: "1305 W Oltorf",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "30.2451764",
    lng: "-97.7688802"
  },
  {
    city: "Austin",
    state: "Texas",
    country: "United States",
    name: "The Backspace",
    website: "http://thebackspace-austin.com",
    address: "507 San Jacinto St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "30.26707249999999",
    lng: "-97.740337"
  },
  {
    city: "Austin",
    state: "Texas",
    country: "United States",
    name: "Bufalina",
    website: "http://www.bufalinapizza.com",
    address: "1519 E Cesar Chavez",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "30.2583421",
    lng: "-97.7289459"
  },
  {
    city: "Austin",
    state: "Texas",
    country: "United States",
    name: "East Side Pies",
    website: "http://eastsidepies.com/",
    address: "1401 Rosewood Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "30.268771",
    lng: "-97.72406749999999"
  },
  {
    city: "Austin",
    state: "Texas",
    country: "United States",
    name: "Home Slice",
    website: "https://www.homeslicepizza.com",
    address: "1415 S Congress Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "30.2492254",
    lng: "-97.7495148"
  },
  {
    city: "Austin",
    state: "Texas",
    country: "United States",
    name: "Little Deli",
    website: "http://www.littledeliandpizza.com/",
    address: "7101 Woodrow Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "30.342657",
    lng: "-97.72545579999999"
  },
  {
    city: "Houston",
    state: "Texas",
    country: "United States",
    name: "Frank's Pizza",
    website: "http://frankspizza.com",
    address: "417 Travis St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "29.761303",
    lng: "-95.362416"
  },
  {
    city: "Longview",
    state: "Texas",
    country: "United States",
    name: "Pizza King",
    website: "http://www.yelp.com/biz/pizza-king-longview",
    address: "1100 E Marshall Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "32.5026725",
    lng: "-94.72566619999999"
  },
  {
    city: "Salt Lake City",
    state: "Utah",
    country: "United States",
    name: "Pie Hole",
    website: "http://pieholeutah.com/index2.html",
    address: "344 S State St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "40.7616447",
    lng: "-111.8886757"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Via 313",
    website: "http://www.via313.com",
    address: "1111 E 6th St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.6154662",
    lng: "-122.190679"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Belltown Pizza",
    website: "http://belltownpizza.net/",
    address: "2422 1st Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.614679",
    lng: "-122.3482796"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Flying Squirrel",
    website: "http://www.flyingsquirrelpizza.com/",
    address: "4920 S. Genesee St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.5643012",
    lng: "-122.2709961"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Flying Squirrel",
    website: "http://www.flyingsquirrelpizza.com/",
    address: "8310 5th Ave NE",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.68928409999999",
    lng: "-122.322766"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Flying Squirrel",
    website: "http://www.flyingsquirrelpizza.com/",
    address: "5701 Airport Way S",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.5511677",
    lng: "-122.3191103"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Humble Pie",
    website: "http://humblepieseattle.com/",
    address: "525 Rainier Avenue South",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.5976234",
    lng: "-122.3131613"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Pagliacci Pizza",
    website: "http://www.pagliacci.com/",
    address: "719 Aurora Ave N",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.6260926",
    lng: "-122.3441629"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Serious Pie",
    website: "http://seriouspieseattle.com/",
    address: "316 Virginia St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.6128967",
    lng: "-122.3405801"
  },
  {
    city: "Seattle",
    state: "Washington",
    country: "United States",
    name: "Via Tribunali",
    website: "http://viatribunali.com/",
    address: "913 E Pike St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "47.613904",
    lng: "-122.3199539"
  },
  {
    city: "Madison",
    state: "Wisconsin",
    country: "United States",
    name: "Grampa's Pizzeria",
    website: "http://grampaspizzeria.com/",
    address: "1374 Williamson St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.0855609",
    lng: "-89.36145370000001"
  },
  {
    city: "Madison",
    state: "Wisconsin",
    country: "United States",
    name: "La Fortuna",
    website: "http://www.lafortunapizza.com/",
    address: "928 O'Sheridan St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.0571399",
    lng: "-89.384636"
  },
  {
    city: "Madison",
    state: "Wisconsin",
    country: "United States",
    name: "Salvatore's Tomato Pies",
    website: "http://salvatorestomatopies.com/",
    address: "912 E Johnson St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.0847998",
    lng: "-89.3760533"
  },
  {
    city: "Leuven",
    state: nil,
    country: "Belgium",
    name: "La Vecchia Napoli",
    website: "http://www.lavecchianapoli.be",
    address: "Pensstraat 6",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "50.8799021",
    lng: "4.6999856"
  },
  {
    city: "Leuven",
    state: nil,
    country: "Belgium",
    name: "Pronto",
    website: "https://plus.google.com/100388940239717823303/about?gl=be&hl=en",
    address: "Muntstraat 14",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "50.878257",
    lng: "4.701861099999999"
  },
  {
    city: "Toronto",
    state: nil,
    country: "Canada",
    name: "Bitondo's Pizzeria",
    website: "https://plus.google.com/111316627016040776065/about?gl=ca&hl=en",
    address: "11 Clinton St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.6541902",
    lng: "-79.4134772"
  },
  {
    city: "Toronto",
    state: nil,
    country: "Canada",
    name: "Pizzeria Libretto",
    website: "http://pizzerialibretto.com/",
    address: "155 University Ave",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.6485343",
    lng: "-79.3848424"
  },
  {
    city: "Peterborough",
    state: nil,
    country: "Canada",
    name: "The Night Kitchen",
    website: "http://www.nightkitchen.ca/",
    address: "229 Hunter St W",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "44.30566049999999",
    lng: "-78.3230679"
  },
  {
    city: "Whistler",
    state: nil,
    country: "Canada",
    name: "Creekbread",
    website: "http://www.creekbread.com/",
    address: "2021 Karen Crescent",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "50.0962398",
    lng: "-122.9912841"
  },
  {
    city: "Cannes",
    state: nil,
    country: "France",
    name: "La Pizza Cresci",
    website: "http://maison-cresci.fr/en",
    address: "3 Quai Saint-Pierre",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "43.550328",
    lng: "7.0119576"
  },
  {
    city: "Paris",
    state: nil,
    country: "France",
    name: "Rossini",
    website: "http://www.yelp.com/biz/rossini-paris-3",
    address: "8 Rue Rossini",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "48.87314929999999",
    lng: "2.3393085"
  },
  {
    city: "Geneva",
    state: nil,
    country: "Switzerland",
    name: "Luigia",
    website: "http://www.luigia.ch/",
    address: "1209, Chemin de la Tourelle 2",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "46.224354",
    lng: "6.1260416"
  },
  {
    city: "Berlin",
    state: nil,
    country: "Germany",
    name: "Trattoria Toscana",
    website: "http://www.toscana-tempelhof.de/",
    address: "SredzkistraÃŸe 49",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "52.5383936",
    lng: "13.4195511"
  },
  {
    city: "Valletta",
    state: nil,
    country: "Malta",
    name: "Vecchia Taranto",
    website: "http://www.tripadvisor.com/Restaurant_Review-g190328-d6674945-Reviews-Pizzeria_Trattoria_Vecchia_Taranto-Valletta_Island_of_Malta.html",
    address: "279 Saint Paul Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "35.8965998",
    lng: "14.5129757"
  },
  {
    city: "Onsala",
    state: nil,
    country: "Sweden",
    name: "Onsala Pizzeria",
    website: "https://www.youtube.com/watch?v=ytXzO8_BMrQ",
    address: "KopparvÃ¤gen 30",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "57.4174234",
    lng: "12.0153723"
  },
  {
    city: "Dar Es Salaam",
    state: nil,
    country: "Tanzania",
    name: "The Waterfront Sunset Restaurant & Beach Bar",
    website: "http://www.tripadvisor.com/Restaurant_Review-g293748-d2264564-Reviews-The_Waterfront_Sunset_Restaurant_Beach_Bar-Dar_es_Salaam_Dar_Es_Salaam_Region.html",
    address: "Msasani Peninsula",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "-6.7473712",
    lng: "39.2816971"
  },
  {
    city: "London",
    state: nil,
    country: "United Kingdom",
    name: "Pizza Pilgrims",
    website: "http://pizzapilgrims.co.uk/",
    address: "11 Dean St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "51.5149223",
    lng: "-0.1332113"
  },
  {
    city: "London",
    state: nil,
    country: "United Kingdom",
    name: "Princi",
    website: "http://www.princi.com/",
    address: "135 Wardour St",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "51.5137578",
    lng: "-0.1343376"
  },
  {
    city: "Southampton",
    state: nil,
    country: "United Kingdom",
    name: "It's a Pizza Thing",
    website: "https://www.facebook.com/apizzathing",
    address: "38-40 Adelaide Rd",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "50.9218994",
    lng: "-1.3874744"
  },
  {
    city: "Glasgow",
    state: nil,
    country: "United Kingdom",
    name: "La Favorita",
    website: "http://lafav.co.uk/glasgow/",
    address: "23-25 Gibson Street",
    marker_size: "medium",
    marker_color: "ffff00",
    marker_symbol: "restaurant",
    lat: "-4.2825091,",
    lng: "55.872322"
  },
])
